### ISSUE TITLE
[Bug]: 0.13.0 fatal issue on compact - Missing required argument: path

### ISSUE THREAD

**Issue by Mostoneman** [MaskPlague/ESLifier#127]
### Check for duplicate issues

- [x] I have verified that there are no open duplicate issues.

### Are you on the latest version?

- [x] I have double checked that I am on the latest version of ESLifier.

### A Brief Description of the Problem.

Since updating to 0.13.0, I can't compact mods anymore because of a python error. I have tried to clean reinstall and it did not fix. It does not seems to be dependant on the pluging being compacted either.

> [2025-10-15T13:00:10.125] An exception has occured, please report this bug to the github and include the ESLifier.log file found in ESLifier_Data.
> [2025-10-15T13:00:10.125] File "main_page.py", line 993, in run
> [2025-10-15T13:00:10.125] File "compact_form_ids.py", line 104, in compact_and_patch
> [2025-10-15T13:00:10.125] File "compact_form_ids.py", line 512, in compact_file
> [2025-10-15T13:00:10.125] File "compact_form_ids.py", line 219, in copy_file_to_output
> [2025-10-15T13:00:10.125] File "compact_form_ids.py", line 252, in get_rel_path
> [2025-10-15T13:00:10.125] Unhandled exception: join() missing 1 required positional argument: 'path'
> exception_hook -> Extended Traceback for debugging:
>   File "main_page.py", line 993, in run
>   File "compact_form_ids.py", line 104, in compact_and_patch
>   File "compact_form_ids.py", line 512, in compact_file
>   File "compact_form_ids.py", line 219, in copy_file_to_output
>   File "compact_form_ids.py", line 252, in get_rel_path

### Provide Relevant Files

[ESLifier.log](https://github.com/user-attachments/files/22925381/ESLifier.log)

**Comment by MaskPlague** [comment]
When you get a chance, try v0.13.1-RC2 on the github. It should work this time. Not sure why this problem never happened before 0.13.0, I did do some refactoring but from looking at it I cannot tell what directly caused this issue. Do you have a loose file in your mods folder directory, outside of any mod folder?

**Comment by Mostoneman** [comment]
It worked! Yes that may be it, I have a single .nif stranded in the data folder.
